version: '3'
services:
  memos:
    image: memosbot:v1
    ports:
      - "3000:8443"
    environment:
      - API_TOKEN=<token>
      # - MODE=webhook
      # - WEBHOOK_HOST=<webhook_host>
      # - WEBHOOK_LISTEN=0.0.0.0
    restart: always
    volumes:
      - <db_path>:/memos/db/
      - <logs_path>:/memos/logs/