version: '3'
services:
  memos:
    image: janzbff/memosbot:v1
    ports:
      - 3000:8443
    environment:
      - API_TOKEN=<api_token>
      # - MODE=webhook
      # - WEBHOOK_HOST=https://tg.janz.eu.org
      # - WEBHOOK_LISTEN=0.0.0.0
    restart: always
    volumes:
      - <db_path>:/memos/db/
      - <logs_path>:/memos/logs/